import { ToolDefinition } from './types.js';

export const TOOLS_REGISTRY: ToolDefinition[] = [
  // 1. Optimize
  {
    id: 'compress',
    name: 'Compress PDF',
    tagline: 'Reduce PDF size with real multi-pass stream optimization',
    description: 'Compress PDF files with 4 presets or specify an exact target file size (e.g. 2MB).',
    category: 'optimize',
    path: '/tools/compress',
    iconName: 'Minimize2',
    popular: true,
    badge: 'Popular',
    acceptedFormats: ['.pdf'],
    maxFiles: 1,
  },

  // 2. Convert
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    tagline: 'Convert DOCX documents to formatted PDF',
    description: 'Preserve headings, paragraphs, lists, and structured tabular data accurately.',
    category: 'convert',
    path: '/tools/word-to-pdf',
    iconName: 'FileText',
    popular: true,
    acceptedFormats: ['.docx'],
    maxFiles: 1,
  },
  {
    id: 'text-to-pdf',
    name: 'Text to PDF',
    tagline: 'Format rich typography and export to PDF',
    description: 'Custom font families, sizes, margins, alignments, and real-time pagination.',
    category: 'convert',
    path: '/tools/text-to-pdf',
    iconName: 'Type',
    acceptedFormats: ['.txt'],
    maxFiles: 1,
  },
  {
    id: 'image-to-pdf',
    name: 'JPG / PNG to PDF',
    tagline: 'Convert images to a unified PDF document',
    description: 'Batch upload multiple images, drag to reorder, and configure page fit modes.',
    category: 'convert',
    path: '/tools/image-to-pdf',
    iconName: 'Image',
    popular: true,
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    maxFiles: 50,
  },
  {
    id: 'pdf-to-image',
    name: 'PDF to JPG / PNG',
    tagline: 'Rasterize PDF pages into high-resolution images',
    description: 'Extract crisp images from each page in PNG or JPEG format and download as ZIP.',
    category: 'convert',
    path: '/tools/pdf-to-image',
    iconName: 'Images',
    acceptedFormats: ['.pdf'],
    maxFiles: 1,
  },
  {
    id: 'pdf-to-text',
    name: 'PDF to Text',
    tagline: 'Extract selectable text and word statistics',
    description: 'Extract text contents with character and word counting, search, and TXT export.',
    category: 'convert',
    path: '/tools/pdf-to-text',
    iconName: 'FileCode',
    acceptedFormats: ['.pdf'],
    maxFiles: 1,
  },

  // 3. Organize & Manage
  {
    id: 'merge',
    name: 'Merge PDF',
    tagline: 'Combine multiple PDFs in custom sequence',
    description: 'Upload multiple PDF files, reorder visually, and merge into a single clean document.',
    category: 'organize',
    path: '/tools/merge',
    iconName: 'Layers',
    popular: true,
    badge: 'Popular',
    acceptedFormats: ['.pdf'],
    maxFiles: 25,
  },
  {
    id: 'split',
    name: 'Split PDF',
    tagline: 'Extract specific pages or ranges to new PDFs',
    description: 'Select page thumbnails visually or enter ranges like 1-3, 5, 8-10 to extract.',
    category: 'organize',
    path: '/tools/split',
    iconName: 'Scissors',
    popular: true,
    acceptedFormats: ['.pdf'],
    maxFiles: 1,
  },
  {
    id: 'rotate',
    name: 'Rotate PDF',
    tagline: 'Rotate pages 90°, 180°, or 270°',
    description: 'Visually rotate single pages or whole documents with instant canvas preview.',
    category: 'organize',
    path: '/tools/rotate',
    iconName: 'RotateCw',
    acceptedFormats: ['.pdf'],
    maxFiles: 1,
  },
  {
    id: 'delete-pages',
    name: 'Delete Pages',
    tagline: 'Remove unwanted pages visually',
    description: 'Click pages to mark for deletion and rebuild a clean document instantly.',
    category: 'organize',
    path: '/tools/delete-pages',
    iconName: 'Trash2',
    acceptedFormats: ['.pdf'],
    maxFiles: 1,
  },
  {
    id: 'reorder-pages',
    name: 'Reorder Pages',
    tagline: 'Rearrange page sequences easily',
    description: 'Drag and drop page thumbnails to reorder pages and export new PDF.',
    category: 'organize',
    path: '/tools/reorder-pages',
    iconName: 'ArrowUpDown',
    acceptedFormats: ['.pdf'],
    maxFiles: 1,
  },

  // 4. Security & Watermark
  {
    id: 'protect',
    name: 'Protect PDF',
    tagline: 'Encrypt PDF with custom password',
    description: 'Secure your document with password encryption and access permissions.',
    category: 'security',
    path: '/tools/protect',
    iconName: 'Lock',
    acceptedFormats: ['.pdf'],
    maxFiles: 1,
  },
  {
    id: 'unlock',
    name: 'Unlock PDF',
    tagline: 'Decrypt password-protected PDFs',
    description: 'Remove security restrictions from authorized PDF files.',
    category: 'security',
    path: '/tools/unlock',
    iconName: 'Unlock',
    acceptedFormats: ['.pdf'],
    maxFiles: 1,
  },
  {
    id: 'watermark',
    name: 'Watermark PDF',
    tagline: 'Add custom text watermark overlays',
    description: 'Custom text, opacity, rotation angle, and layer depth for document protection.',
    category: 'security',
    path: '/tools/watermark',
    iconName: 'Stamp',
    acceptedFormats: ['.pdf'],
    maxFiles: 1,
  },
  {
    id: 'signature',
    name: 'Sign PDF',
    tagline: 'Draw signature and stamp onto document',
    description: 'Interactive HTML5 canvas signature pad with drag-and-drop page placement.',
    category: 'security',
    path: '/tools/signature',
    iconName: 'PenTool',
    acceptedFormats: ['.pdf'],
    maxFiles: 1,
  },
];
